const responseObj = {
  "Buna": "Bună, sunt BioMin , un AI destinat să te ajute în oferirea unei baze largi de informații legate de nivelul de poluare  global, european sau local. În același timp, pot să îți ofer date legate de poluarea in orase.",
  "Date despre Asia":" Asia este recunoscută pentru nivelurile ridicate de poluare a aerului în multe dintre orașele sale mari. Emisiile industriale, traficul intens și utilizarea extensivă a cărbunelui pentru producerea de energie sunt factori majori. Orasele precum New Delhi si  Beijing  sunt notorii pentru nivelurile de smog și particule în aer.",
  "Date despre America":" Deși standardele de calitate a aerului sunt relativ ridicate în multe părți ale Americii, există încă zone în care poluarea aerului reprezintă o problemă semnificativă. Orașe mari precum Los Angeles, New York și Mexico City se confruntă cu probleme de smog și niveluri ridicate de poluare a aerului, generate în principal de emisiile vehiculelor și industriale.",
  "Date despre Europa":"Poluarea în Europa este o problemă serioasă, care afectează atât mediul înconjurător, cât și sănătatea oamenilor.Unele orașe europene, precum București, Sofia, și Varșovia, se confruntă cu niveluri ridicate de poluare a aerului, în special din cauza traficului intens și a emisiilor industriale. Particulele fine și oxidul de azot sunt printre principalele surses care afectează sănătatea locuitorilor.",
  "Date despre Rusia":"Rusia se confruntă cu niveluri ridicate de poluare a aerului în mai multe orașe mari, precum Moscova, Sankt Petersburg și Novosibirsk. Emisiile provenite din industrie, traficul intens și utilizarea cărbunelui pentru încălzire sunt principalele surse de poluare a aerului.",
  "Orase Europene":"Cele mai poluate orașe din Europa variază în funcție de diversele tipuri de poluare, cum ar fi poluarea aerului, poluarea fonica și altele.Câteva exemple de orașe europene cunoscute pentru nivelurile ridicate de poluare includ Bucureștiul (România), Sofia (Bulgaria), Skopje (Macedonia de Nord), Tirana (Albania), Belgrad (Serbia), Istanbul (Turcia) și Varșovia (Polonia).",
  "Date despre Sofia":"Poluarea aerului este una dintre cele mai mari probleme din Sofia. Emisiile provenite din traficul intens, industrie și încălzirea locuințelor cu cărbune contribuie la creșterea concentrațiilor de particule în aer, precum și a nivelurilor de dioxid de azot și monoxid de carbon.",
  "Date despre Skopje":"Skopje are una dintre cele mai proaste calități a aerului din Europa. Poluarea aerului este cauzată în principal de la numărul mare de vehicule, inclusiv vehiculele mai vechi și mai poluante, .Contribuie semnificativ la nivelurile ridicate de poluare din oraș încălzirea locuințelor cu cărbune și lemn, precum și emisiile industriale.",
  "Date despre Tirana":"Mulți locuitori din Tirana folosesc cărbune și lemn pentru încălzirea locuințelor în timpul sezonului rece. Arderea acestor combustibili în sistemele de încălzire casnică este o sursă importantă de emisii de particule fine și alte poluanți.Autoritățile din Tirana iau anumite măsuri pentru a combate poluarea, cum ar fi promovarea transportului public, încurajarea utilizării vehiculelor electrice sau cu emisii reduse și implementarea unor programe de monitorizare a calității aerului.",
  "Date despre Romania":"Principalele surse de poluare a aerului în România includ industria grea, centralele termice, transportul rutier, încălzirea locuințelor și industria minieră. Emisiile de particule fine, dioxid de sulf, dioxid de azot și alte substanțe nocive au un impact semnificativ asupra calității aerului.România, a fost subiectul unor dispute intense și controverse în ultimii ani, în legătură cu implicarea companiei Gabriel Resources și planurile sale de a dezvolta o mină de aur la scară largă în zonă.",
  "Date despre orase":"Principalele orașe din România sunt: București (capitala), Iași, Brașov, Cluj-Napoca, Constanța și Timișoara",
  "Date despre Bucuresti":"Principalele surse de poluare din București includ monoxidul de carbon (CO), dioxidul de azot (NO₂), ozonul (O₃), particulele în suspensie (PM10 și PM2.5), dioxidul de sulf (SO₂), hidrocarburile și plumbul. Te intereseaza o anumita zona din Bucuresti",
  "Gara de Nord":"În momentul de față, la data de 27 Iunie 2024, în zona Gării de Nord a capitalei am înregistrat o valoare de 8 ICA. Acestea sunt valori foarte scăzute conform indicilor de poluare pentru aer . Dacă ești interesat de alte zone, te rog să specifici acea zonă.",
  "Zona Baneasa":"In momentul de față, la data de 27 Iunie 2024, în zona Băneasa  a capitalei am înregistrat o valoare de 30 ICA . Acestea sunt valori scăzute conform indicilor de poluare. Dacă ești interesat de alte zone, te rog să specifici acea zonă.",
  "Piata Victoriei":"In momentul de față, la data de 27 Iunie 2024, în zona Victoriei  a capitalei am înregistrat o valoare de 55 pe Indicele de calitate a aerului (ICA) . Acestea sunt valori ridicate conform indicilor de poluare. Dacă ești interesat de alte zone, te rog să specifici acea zonă.",
  "Berceni":"In momentul de față, la data de 27 Iunie 2024, în zona Berceni  a capitalei am înregistrat o valoare de 40 pe Indicele de calitate a aerului (ICA) . Acestea sunt valori ridicate conform indicilor de poluare. Dacă ești interesat de alte zone, te rog să specifici acea zonă.",
  "Pantelimon":"In momentul de față, la data de 27 Iunie 2024, în zona Pantelimon  a capitalei am înregistrat o valoare de 14 pe Indicele de calitate a aerului (ICA) . Acestea sunt valori scazute conform indicilor de poluare. Dacă ești interesat de alte zone, te rog să specifici acea zonă.",
  "Titan":"In momentul de față, la data de 27 Iunie 2024, în zona Titan  a capitalei am înregistrat o valoare de 44 pe Indicele de calitate a aerului (ICA) . Acestea sunt valori ridicate conform indicilor de poluare. Dacă ești interesat de alte zone, te rog să specifici acea zonă.",
  "Drumul Taberei":"In momentul de față, la data de 27 Iunie 2024, în zona Drumul Taberei   a capitalei am înregistrat o valoare de 12 pe Indicele de calitate a aerului (ICA) . Acestea sunt valori scazute  conform indicilor de poluare. Dacă ești interesat de alte zone, te rog să specifici acea zonă.",
  "Zona Expozitiei":"In momentul de față, la data de 27 Iunie 2024, în zona Expozitiei   a capitalei am înregistrat o valoare de 9 pe Indicele de calitate a aerului (ICA) . Acestea sunt valori scazute  conform indicilor de poluare. Dacă ești interesat de alte zone, te rog să specifici acea zonă",
  };
  


